set -g base-index 1
set -s escape-time 0
set -g mouse on
setw -g pane-base-index 1
set -g renumber-windows on
set -g status-left ""
set -g status-right ""
bind c new-window -c "#{pane_current_path}"
bind Left swap-window -t -1\; select-window -t -1
bind-key Right swap-window -t +1\; select-window -t +1


set -ag terminal-overrides ",alacritty:RGB"
set -g default-terminal "${TERM}"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colors
