vim.keymap.set("n", "<Esc>", ":nohlsearch<return><Esc>", { noremap = true, silent = true })
vim.keymap.set({ "n", "i" }, "<C-c>", "<Esc>", { remap = true })
vim.keymap.set("n", "<C-h>", "<C-w>h", { noremap = true })
vim.keymap.set("n", "<C-j>", "<C-w>j", { noremap = true })
vim.keymap.set("n", "<C-k>", "<C-w>k", { noremap = true })
vim.keymap.set("n", "<C-l>", "<C-w>l", { noremap = true })
vim.keymap.set("n", "<Leader>q", "<C-w>q", { noremap = true })
vim.keymap.set("n", "<Leader>v", "<C-w>v", { noremap = true })
vim.keymap.set("n", "<Leader>s", "<C-w>s", { noremap = true })

vim.keymap.set("x", "<Leader>p", "pgvy", { noremap = true })
vim.keymap.set({ "n", "x" }, "<Leader>c", '"_c', { noremap = true })
vim.keymap.set({ "n", "x" }, "<Leader>d", '"_d', { noremap = true })

vim.keymap.set("n", "{", "{zz", { noremap = true })
vim.keymap.set("n", "}", "}zz", { noremap = true })
vim.keymap.set("n", "<C-u>", "<C-u>zz", { noremap = true })
vim.keymap.set("n", "<C-d>", "<C-d>zz", { noremap = true })
vim.keymap.set("n", "*", "*``zz", { noremap = true, silent = true })
vim.keymap.set("v", "*", "\"sy /\\V<C-r>s<CR>``zz", { noremap = true, silent = true })
vim.keymap.set("n", "n", "nzz", { noremap = true })
vim.keymap.set("n", "N", "Nzz", { noremap = true })
vim.keymap.set("n", "<C-i>", "<C-i>zz", { noremap = true })
vim.keymap.set("n", "<C-o>", "<C-o>zz", { noremap = true })

vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
