vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>")

vim.keymap.set("n", "<C-h>", "<C-w><C-h>")
vim.keymap.set("n", "<C-l>", "<C-w><C-l>")
vim.keymap.set("n", "<C-j>", "<C-w><C-j>")
vim.keymap.set("n", "<C-k>", "<C-w><C-k>")

vim.keymap.set("x", "<leader>p", "pgvy", { noremap = true })
vim.keymap.set({ "n", "x" }, "<leader>c", '"_c', { noremap = true })
vim.keymap.set({ "n", "x" }, "<leader>d", '"_d', { noremap = true })
vim.keymap.set({ "n", "x" }, "<leader>x", '"_x', { noremap = true })

vim.keymap.set({ "n", "x" }, "{", "{zz", { noremap = true })
vim.keymap.set({ "n", "x" }, "}", "}zz", { noremap = true })
vim.keymap.set({ "n", "x" }, "<C-u>", "<C-u>zz", { noremap = true })
vim.keymap.set({ "n", "x" }, "<C-d>", "<C-d>zz", { noremap = true })
vim.keymap.set("n", "n", "nzz", { noremap = true })
vim.keymap.set("n", "N", "Nzz", { noremap = true })
vim.keymap.set("n", "<C-i>", "<C-i>zz", { noremap = true })
vim.keymap.set("n", "<C-o>", "<C-o>zz", { noremap = true })
